services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: web_commission_image:latest
    restart: unless-stopped
    env_file: .env
    ports:
      - "${DOCKER_EXPOSE_PORT:-8000}:${DJANGO_PORT:-8000}"
    command: poetry run gunicorn core.asgi:application --bind :${DJANGO_PORT:-8000} --workers 8 --worker-class uvicorn.workers.UvicornWorker --timeout 120
