services:
  redis:
    image: redis:5.0
    restart: unless-stopped

#  celery:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    restart: unless-stopped
#    env_file: .env
#    depends_on:
#      - redis
#    command: poetry run celery -A core worker --loglevel=info