[tool.poetry]
name = "overwatch"
version = "0.1.0"
description = ""
authors = ["fattakhoval <fattahoval66@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.1.4"
channels = "^4.2.0"
websockets = "^14.1"
whitenoise = "^6.8.2"
requests = "^2.32.3"
django-registration = "^5.1.0"
gunicorn = "^23.0.0"
uvicorn = "^0.34.0"
mysqlclient = "^2.2.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
